---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04

suites:
- name: clients
  run_list:
    - recipe[mariadb::client]
  attributes:
- name: servers
  run_list:
    - recipe[mariadb::server]
  attributes:
    mariadb:
      server_debian_password: 'ilovestrongpasswords'
      server_root_password:   'ilovestrongpasswords'
      server_repl_password:   'ilovestrongpasswords'
